"""Output writers for XYZ, LAMMPS, GROMACS, and JSON metadata."""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

from .topology import System
from .utils import ensure_parent, json_ready


def write_xyz(system: System, path: str | Path) -> Path:
    """Write a simple XYZ file."""

    out = ensure_parent(path)
    labels = system.labels or [f"T{atom_type}" for atom_type in system.atom_types]
    with out.open("w", encoding="utf-8") as handle:
        handle.write(f"{system.n_atoms}\n")
        handle.write("generated by polygraft_builder\n")
        for label, (x, y, z) in zip(labels, system.positions):
            handle.write(f"{label} {x:.8f} {y:.8f} {z:.8f}\n")
    return out


def write_lammps_data(system: System, path: str | Path) -> Path:
    """Write a minimal LAMMPS molecular data file with atoms and bonds."""

    out = ensure_parent(path)
    mins = np.min(system.positions, axis=0) - 2.0
    maxs = np.max(system.positions, axis=0) + 2.0
    atom_type_count = int(np.max(system.atom_types))
    bond_type_count = int(max(system.bond_types) if system.bond_types else 0)
    with out.open("w", encoding="utf-8") as handle:
        handle.write("LAMMPS data file generated by polygraft_builder\n\n")
        handle.write(f"{system.n_atoms} atoms\n")
        handle.write(f"{system.n_bonds} bonds\n\n")
        handle.write(f"{atom_type_count} atom types\n")
        handle.write(f"{bond_type_count} bond types\n\n")
        handle.write(f"{mins[0]:.8f} {maxs[0]:.8f} xlo xhi\n")
        handle.write(f"{mins[1]:.8f} {maxs[1]:.8f} ylo yhi\n")
        handle.write(f"{mins[2]:.8f} {maxs[2]:.8f} zlo zhi\n\n")
        handle.write("Masses\n\n")
        for atom_type in range(1, atom_type_count + 1):
            handle.write(f"{atom_type} 1.0\n")
        handle.write("\nAtoms # molecular\n\n")
        for atom_id, (atom_type, (x, y, z)) in enumerate(zip(system.atom_types, system.positions), start=1):
            molecule_id = 1
            handle.write(f"{atom_id} {molecule_id} {int(atom_type)} {x:.8f} {y:.8f} {z:.8f}\n")
        if system.bonds:
            handle.write("\nBonds\n\n")
            for bond_id, ((a, b), bond_type) in enumerate(zip(system.bonds, system.bond_types), start=1):
                handle.write(f"{bond_id} {int(bond_type)} {a + 1} {b + 1}\n")
    return out


def write_gro(system: System, path: str | Path, box_padding: float = 2.0) -> Path:
    """Write a minimal GROMACS ``.gro`` coordinate file."""

    out = ensure_parent(path)
    labels = system.labels or [f"T{atom_type}" for atom_type in system.atom_types]
    shifted, box = _shifted_positions_and_box(system.positions, box_padding)
    with out.open("w", encoding="utf-8") as handle:
        handle.write("generated by polygraft_builder\n")
        handle.write(f"{system.n_atoms:5d}\n")
        for atom_id, (label, atom_type, (x, y, z)) in enumerate(
            zip(labels, system.atom_types, shifted),
            start=1,
        ):
            res_id = 1
            res_name = _gro_name("PGF")
            atom_name = _gro_name(_atom_type_name(int(atom_type), label))
            handle.write(
                f"{res_id % 100000:5d}{res_name:<5}{atom_name:>5}"
                f"{atom_id % 100000:5d}{x:8.3f}{y:8.3f}{z:8.3f}\n"
            )
        handle.write(f"{box[0]:10.5f}{box[1]:10.5f}{box[2]:10.5f}\n")
    return out


def write_gromacs_itp(system: System, path: str | Path, molecule_name: str = "POLYG") -> Path:
    """Write a simple GROMACS molecule include file with atoms and bonds."""

    out = ensure_parent(path)
    labels = system.labels or [f"T{atom_type}" for atom_type in system.atom_types]
    with out.open("w", encoding="utf-8") as handle:
        handle.write("; generated by polygraft_builder\n")
        handle.write("[ moleculetype ]\n")
        handle.write("; name  nrexcl\n")
        handle.write(f"{molecule_name}  1\n\n")
        handle.write("[ atoms ]\n")
        handle.write("; nr  type  resnr  residue  atom  cgnr  charge  mass\n")
        for atom_id, (atom_type, label) in enumerate(zip(system.atom_types, labels), start=1):
            atom_name = _atom_type_name(int(atom_type), label)
            handle.write(
                f"{atom_id:5d} {_gmx_type_name(int(atom_type)):>6} {1:5d} "
                f"{'PGF':>6} {atom_name:>6} {atom_id:5d} {0.0:8.3f} {1.0:8.3f}\n"
            )
        if system.bonds:
            handle.write("\n[ bonds ]\n")
            handle.write("; ai  aj  funct\n")
            for a, b in system.bonds:
                handle.write(f"{a + 1:5d} {b + 1:5d} {1:5d}\n")
    return out


def write_gromacs_topology(
    system: System,
    path: str | Path,
    itp_filename: str,
    molecule_name: str = "POLYG",
) -> Path:
    """Write a minimal GROMACS ``.top`` file that includes the molecule ITP."""

    out = ensure_parent(path)
    atom_types = sorted({int(atom_type) for atom_type in system.atom_types})
    with out.open("w", encoding="utf-8") as handle:
        handle.write("; generated by polygraft_builder\n")
        handle.write("[ defaults ]\n")
        handle.write("; nbfunc  comb-rule  gen-pairs  fudgeLJ  fudgeQQ\n")
        handle.write("1  1  no  1.0  1.0\n\n")
        handle.write("[ atomtypes ]\n")
        handle.write("; name  mass  charge  ptype  sigma  epsilon\n")
        for atom_type in atom_types:
            handle.write(f"{_gmx_type_name(atom_type):>6} {1.0:8.3f} {0.0:8.3f} A {1.0:8.3f} {1.0:8.3f}\n")
        handle.write(f'\n#include "{itp_filename}"\n\n')
        handle.write("[ system ]\n")
        handle.write("polygraft_builder system\n\n")
        handle.write("[ molecules ]\n")
        handle.write("; name  count\n")
        handle.write(f"{molecule_name}  1\n")
    return out


def write_json(path: str | Path, metadata: dict) -> Path:
    """Write JSON metadata."""

    out = ensure_parent(path)
    out.write_text(json.dumps(json_ready(metadata), indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return out


def write_system_outputs(system: System, out: str | Path) -> dict[str, str]:
    """Write outputs based on the requested extension plus metadata.

    Each builder command leaves a complete set of portable outputs: XYZ,
    LAMMPS data, GROMACS GRO/ITP/TOP, and JSON metadata.
    """

    out_path = ensure_parent(out)
    stem = out_path.with_suffix("")
    xyz_path = out_path if out_path.suffix == ".xyz" else stem.with_suffix(".xyz")
    lammps_path = (
        out_path
        if out_path.suffix in {".lammps", ".data", ".lammpsdata"}
        else stem.with_suffix(".lammps")
    )
    json_path = stem.with_suffix(".json")
    gro_path = out_path if out_path.suffix == ".gro" else stem.with_suffix(".gro")
    itp_path = out_path if out_path.suffix == ".itp" else stem.with_suffix(".itp")
    top_path = out_path if out_path.suffix == ".top" else stem.with_suffix(".top")
    write_xyz(system, xyz_path)
    write_lammps_data(system, lammps_path)
    write_gro(system, gro_path)
    write_gromacs_itp(system, itp_path)
    write_gromacs_topology(system, top_path, itp_path.name)
    write_json(
        json_path,
        {
            "n_atoms": system.n_atoms,
            "n_bonds": system.n_bonds,
            "atom_types": system.atom_types.tolist(),
            "bonds": system.bonds,
            **system.metadata,
        },
    )
    return {
        "xyz": str(xyz_path),
        "lammps": str(lammps_path),
        "gro": str(gro_path),
        "itp": str(itp_path),
        "top": str(top_path),
        "json": str(json_path),
    }


def _shifted_positions_and_box(positions: np.ndarray, padding: float) -> tuple[np.ndarray, np.ndarray]:
    mins = np.min(positions, axis=0)
    maxs = np.max(positions, axis=0)
    shifted = positions - mins + padding
    box = maxs - mins + 2.0 * padding
    return shifted, box


def _atom_type_name(atom_type: int, label: str) -> str:
    label = label.strip().upper()
    if label in {"A", "B", "NP", "CORE"}:
        return label
    return {
        1: "A",
        2: "B",
        3: "NP",
        4: "CORE",
    }.get(atom_type, f"T{atom_type}")


def _gmx_type_name(atom_type: int) -> str:
    return {
        1: "PGA",
        2: "PGB",
        3: "PGN",
        4: "PGC",
    }.get(atom_type, f"PG{atom_type}")


def _gro_name(name: str) -> str:
    return name[:5]
