"""Output writers for XYZ, LAMMPS data, and JSON metadata."""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

from .topology import System
from .utils import ensure_parent, json_ready


def write_xyz(system: System, path: str | Path) -> Path:
    """Write a simple XYZ file."""

    out = ensure_parent(path)
    labels = system.labels or [f"T{atom_type}" for atom_type in system.atom_types]
    with out.open("w", encoding="utf-8") as handle:
        handle.write(f"{system.n_atoms}\n")
        handle.write("generated by polygraft_builder\n")
        for label, (x, y, z) in zip(labels, system.positions):
            handle.write(f"{label} {x:.8f} {y:.8f} {z:.8f}\n")
    return out


def write_lammps_data(system: System, path: str | Path) -> Path:
    """Write a minimal LAMMPS molecular data file with atoms and bonds."""

    out = ensure_parent(path)
    mins = np.min(system.positions, axis=0) - 2.0
    maxs = np.max(system.positions, axis=0) + 2.0
    atom_type_count = int(np.max(system.atom_types))
    bond_type_count = int(max(system.bond_types) if system.bond_types else 0)
    with out.open("w", encoding="utf-8") as handle:
        handle.write("LAMMPS data file generated by polygraft_builder\n\n")
        handle.write(f"{system.n_atoms} atoms\n")
        handle.write(f"{system.n_bonds} bonds\n\n")
        handle.write(f"{atom_type_count} atom types\n")
        handle.write(f"{bond_type_count} bond types\n\n")
        handle.write(f"{mins[0]:.8f} {maxs[0]:.8f} xlo xhi\n")
        handle.write(f"{mins[1]:.8f} {maxs[1]:.8f} ylo yhi\n")
        handle.write(f"{mins[2]:.8f} {maxs[2]:.8f} zlo zhi\n\n")
        handle.write("Masses\n\n")
        for atom_type in range(1, atom_type_count + 1):
            handle.write(f"{atom_type} 1.0\n")
        handle.write("\nAtoms # molecular\n\n")
        for atom_id, (atom_type, (x, y, z)) in enumerate(zip(system.atom_types, system.positions), start=1):
            molecule_id = 1
            handle.write(f"{atom_id} {molecule_id} {int(atom_type)} {x:.8f} {y:.8f} {z:.8f}\n")
        if system.bonds:
            handle.write("\nBonds\n\n")
            for bond_id, ((a, b), bond_type) in enumerate(zip(system.bonds, system.bond_types), start=1):
                handle.write(f"{bond_id} {int(bond_type)} {a + 1} {b + 1}\n")
    return out


def write_json(path: str | Path, metadata: dict) -> Path:
    """Write JSON metadata."""

    out = ensure_parent(path)
    out.write_text(json.dumps(json_ready(metadata), indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return out


def write_system_outputs(system: System, out: str | Path) -> dict[str, str]:
    """Write outputs based on the requested extension plus metadata.

    XYZ requests also write a LAMMPS file, and LAMMPS requests also write an XYZ
    file, so each builder command leaves a complete trio of outputs.
    """

    out_path = ensure_parent(out)
    stem = out_path.with_suffix("")
    xyz_path = out_path if out_path.suffix == ".xyz" else stem.with_suffix(".xyz")
    lammps_path = (
        out_path
        if out_path.suffix in {".lammps", ".data", ".lammpsdata"}
        else stem.with_suffix(".lammps")
    )
    json_path = stem.with_suffix(".json")
    write_xyz(system, xyz_path)
    write_lammps_data(system, lammps_path)
    write_json(
        json_path,
        {
            "n_atoms": system.n_atoms,
            "n_bonds": system.n_bonds,
            "atom_types": system.atom_types.tolist(),
            "bonds": system.bonds,
            **system.metadata,
        },
    )
    return {"xyz": str(xyz_path), "lammps": str(lammps_path), "json": str(json_path)}
